# Generated by Django 2.1.5 on 2019-01-19 21:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='WirelessClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=50)),
                ('human_name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clientconnection',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowd.WirelessClient'),
        ),
        migrations.AddField(
            model_name='clientconnection',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowd.BaseStation'),
        ),
    ]
