# Generated by Django 2.1.5 on 2019-01-20 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basestation',
            name='token',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
