# Generated by Django 2.1.5 on 2019-01-20 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0003_auto_20190120_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconnection',
            name='channel',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='clientconnection',
            name='gain',
            field=models.FloatField(null=True),
        ),
    ]
