# Generated by Django 2.1.5 on 2019-01-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowd', '0004_auto_20190120_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientconnection',
            name='time',
            field=models.PositiveIntegerField(),
        ),
    ]
